### ISSUE TITLE
мудак ты!

### ISSUE THREAD

**Issue by dcbeelinekz** [den67rus/ptokax-install-source#2]

**Comment by den67rus** [comment]
Веди себя прилично.

**Comment by dcbeelinekz** [comment]
а че ты как черт сразу, шуганный пидарас, сразу в бан . гандон сука. Если зазнался в чем то сиди как сидел ,нахуй ты не нужен чтоб у тебя теперь что то спрашивать, если ты нихуя сам не знаешь!!

**Comment by den67rus** [comment]
На github указан e-mail для связи, это общепринятый способ общения. А писать и добавятся в друзья в соц. сетях не совсем логичных ход. К тому же данный пакет не поддерживается более 5 лет. А кричать и обзываться, а потом просить о помощи так себе идея. К тому же у PtokaX есть форум, где присутствует непосредственно разработчик http://forum.ptokax.org/ он скорее всего сможет ответить на твой вопрос.

**Comment by dcbeelinekz** [comment]
Лан извянки.  
А к этим пидарам я пытался написать http://forum.ptokax.org то рега не проходит блять!
